/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Class.*;
import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;



/**
 *
 * @author PC
 */
public class FrmPrincipal extends javax.swing.JFrame {

    //Atributos de la Clase
   
    private MaquinaDiesel objDiesel = new MaquinaDiesel(2000,40);
    private MaquinaCorriente objCorriente = new MaquinaCorriente(3000, 30);
    private Maquinaextra objMaquinaextra = new Maquinaextra(4000, 80);
     
   // private MaquinaSurtidora objetoMachine = new MaquinaSurtidora();
   //   private frmTipoCombustible uno = new frmTipoCombustible(objDiesel);
    
   // private MaquinaSurtidora objMaquina1 = new MaquinaSurtidora("COMBUSTIBLE DIESEL",2000,40);
   // private MaquinaSurtidora objMaquina2 = new MaquinaSurtidora("COMBUSTIBLE CORRIENTE",5000,20);
    
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        //objDiesel.getMontoVendido();
        jPanel1.setBackground(new Color(44, 184, 171  ));
        panelDashboard.setBackground(new  Color(44, 184, 171  ));
        btnDiesel.setBackground(new  Color(44, 184, 171  ));
        btnCorriente.setBackground(new  Color(44, 184, 171  ));
        btnExtra.setBackground(new  Color(44, 184, 171  ));
        //ocultoVentas1.setText(String.valueOf(objDiesel.getMontoVendido()));
        
        
        
    }

    public void MostrarDashboard(){
        ocultoVentas1.setText(String.valueOf(objDiesel.getCantidadVentas()));
        montoOculto1.setText(String.valueOf(objDiesel.getMontoAcumulado()));
        vendidosLOculto1.setText(String.valueOf(objDiesel.getLitrosAcumulados()));
        disponiblesOculto1.setText(String.valueOf(objDiesel.getDisponibilidadTanque()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDiesel = new javax.swing.JButton();
        btnCorriente = new javax.swing.JButton();
        btnExtra = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelDashboard = new javax.swing.JPanel();
        diesel1 = new javax.swing.JLabel();
        corriente1 = new javax.swing.JLabel();
        extra1 = new javax.swing.JLabel();
        cantVentas = new javax.swing.JLabel();
        montoventas = new javax.swing.JLabel();
        litrosVendidos = new javax.swing.JLabel();
        litrosDisponibles = new javax.swing.JLabel();
        ocultoVentas1 = new javax.swing.JLabel();
        montoOculto1 = new javax.swing.JLabel();
        vendidosLOculto1 = new javax.swing.JLabel();
        disponiblesOculto1 = new javax.swing.JLabel();
        ocultoVentas2 = new javax.swing.JLabel();
        montoOculto2 = new javax.swing.JLabel();
        vendidosLOculto2 = new javax.swing.JLabel();
        disponiblesOculto2 = new javax.swing.JLabel();
        ocultoVentas3 = new javax.swing.JLabel();
        montoOculto3 = new javax.swing.JLabel();
        vendidosLOculto3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("TIPOS DE COMBUSTIBLES"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDiesel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnDiesel.setText("DIESEL");
        btnDiesel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDieselMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDieselMouseExited(evt);
            }
        });
        btnDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDieselActionPerformed(evt);
            }
        });
        jPanel1.add(btnDiesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 137, 58));

        btnCorriente.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCorriente.setText("CORRIENTE");
        btnCorriente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCorrienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCorrienteMouseExited(evt);
            }
        });
        btnCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 137, 58));

        btnExtra.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnExtra.setText("EXTRA");
        btnExtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExtraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExtraMouseExited(evt);
            }
        });
        btnExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraActionPerformed(evt);
            }
        });
        jPanel1.add(btnExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 137, 58));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setText("Turnos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1083, 63, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 150));

        panelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diesel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        diesel1.setText("Diesel");
        panelDashboard.add(diesel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 22, -1, -1));

        corriente1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        corriente1.setText("Corriente");
        panelDashboard.add(corriente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 22, -1, -1));

        extra1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        extra1.setText("Extra");
        panelDashboard.add(extra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 22, -1, -1));

        cantVentas.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cantVentas.setText("Cantidad de ventas");
        panelDashboard.add(cantVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, -1, -1));

        montoventas.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        montoventas.setText("Monto ventas");
        panelDashboard.add(montoventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, -1, -1));

        litrosVendidos.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        litrosVendidos.setText("Litros vendidos");
        panelDashboard.add(litrosVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 315, -1, -1));

        litrosDisponibles.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        litrosDisponibles.setText("Litros disponibles");
        panelDashboard.add(litrosDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 412, -1, -1));

        ocultoVentas1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ocultoVentas1.setText("         0");
        panelDashboard.add(ocultoVentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 93, -1, -1));

        montoOculto1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        montoOculto1.setText("      $ 0");
        panelDashboard.add(montoOculto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 204, -1, -1));

        vendidosLOculto1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        vendidosLOculto1.setText("          0 L.");
        panelDashboard.add(vendidosLOculto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 87, 31));

        disponiblesOculto1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        disponiblesOculto1.setText("         L.");
        panelDashboard.add(disponiblesOculto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 412, -1, -1));

        ocultoVentas2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ocultoVentas2.setText("         0");
        panelDashboard.add(ocultoVentas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        montoOculto2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        montoOculto2.setText("      $ 0");
        panelDashboard.add(montoOculto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        vendidosLOculto2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        vendidosLOculto2.setText("        0 L.");
        panelDashboard.add(vendidosLOculto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));

        disponiblesOculto2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        disponiblesOculto2.setText("          L.");
        panelDashboard.add(disponiblesOculto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, -1, -1));

        ocultoVentas3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ocultoVentas3.setText("       0");
        panelDashboard.add(ocultoVentas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, -1, -1));

        montoOculto3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        montoOculto3.setText("     $ 0");
        panelDashboard.add(montoOculto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, -1, -1));

        vendidosLOculto3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        vendidosLOculto3.setText("       0 L.");
        panelDashboard.add(vendidosLOculto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setText("          L.");
        panelDashboard.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, -1, -1));

        getContentPane().add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1390, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDieselActionPerformed
        
        frmTipoCombustible objFrm = new frmTipoCombustible(objDiesel, this);
        objFrm.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_btnDieselActionPerformed

    private void btnCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrienteActionPerformed
        frmTipoCombustible objFrm = new frmTipoCombustible(objCorriente, this);
        objFrm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCorrienteActionPerformed

    private void btnDieselMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDieselMouseEntered
        // TODO add your handling code here:
        btnDiesel.setBackground(new Color(53, 215, 200  ));
    }//GEN-LAST:event_btnDieselMouseEntered

    private void btnDieselMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDieselMouseExited
        // TODO add your handling code here:
        btnDiesel.setBackground(new  Color(44, 184, 171  ));
    }//GEN-LAST:event_btnDieselMouseExited

    private void btnCorrienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCorrienteMouseEntered
        // TODO add your handling code here:
        btnCorriente.setBackground(new Color(53, 215, 200  ));
    }//GEN-LAST:event_btnCorrienteMouseEntered

    private void btnCorrienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCorrienteMouseExited
        // TODO add your handling code here:
        btnCorriente.setBackground(new  Color(44, 184, 171  ));
    }//GEN-LAST:event_btnCorrienteMouseExited

    private void btnExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraActionPerformed
        // TODO add your handling code here:
        frmTipoCombustible objExtra = new frmTipoCombustible(objMaquinaextra,this);
        objExtra.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnExtraActionPerformed

    private void btnExtraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExtraMouseEntered
        // TODO add your handling code here:
        btnExtra.setBackground(new Color(53, 215, 200  ));
    }//GEN-LAST:event_btnExtraMouseEntered

    private void btnExtraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExtraMouseExited
        // TODO add your handling code here:
        btnExtra.setBackground(new  Color(44, 184, 171  ));
    }//GEN-LAST:event_btnExtraMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        employee empleados = new employee();
        empleados.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCorriente;
    private javax.swing.JButton btnDiesel;
    private javax.swing.JButton btnExtra;
    private javax.swing.JLabel cantVentas;
    private javax.swing.JLabel corriente1;
    private javax.swing.JLabel diesel1;
    public static javax.swing.JLabel disponiblesOculto1;
    public static javax.swing.JLabel disponiblesOculto2;
    private javax.swing.JLabel extra1;
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel litrosDisponibles;
    private javax.swing.JLabel litrosVendidos;
    public static javax.swing.JLabel montoOculto1;
    public static javax.swing.JLabel montoOculto2;
    public static javax.swing.JLabel montoOculto3;
    private javax.swing.JLabel montoventas;
    public transient javax.swing.JLabel ocultoVentas1;
    public static javax.swing.JLabel ocultoVentas2;
    public static javax.swing.JLabel ocultoVentas3;
    private javax.swing.JPanel panelDashboard;
    public static javax.swing.JLabel vendidosLOculto1;
    public static javax.swing.JLabel vendidosLOculto2;
    public static javax.swing.JLabel vendidosLOculto3;
    // End of variables declaration//GEN-END:variables
}
